### PR TITLE
DRY "${home_dir_path}/.k5login" with $k5login_path

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Review by mattock — APPROVED** [review]
Looks good, thank you!

**Comment by mattock** [comment]
Once the conflict is resolved I'll merge this.

**Comment by jhoblitt** [comment]
@mattock I missed that this PR hadn't been merged. 

Rebased on current master.

**Comment by jhoblitt** [comment]
@mattock I would like this PR to be merged prior #21, so that #21 can be rebased on top of this cleanup.

**Pull request merged**
