### PR TITLE
Modulesync

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by jhoblitt** [comment]
@mattock It doesn't look like gha has triggered. Is it asking you to approve running gha for this PR?

**Comment by jhoblitt** [comment]
Doesn't look like gha is working yet.

**Comment by mattock** [comment]
I checked GitHub Actions settings and they looked ok. Perhaps GHA will kick in after this PR is merged.

**Comment by mattock** [comment]
Let's just merge this. If GHA does not work on the next PR then I will dig in more deeply.

**Pull request merged**
